package generator

import (
	"fmt"
	"io"
	"strings"
)

type dumpCommentOption struct {
	mockgenCmd     string
	destination    string
	packageName    string
	sourcePackage  string
	interfaceNames []string
}

func dumpComment(opt *dumpCommentOption) string {
	joinedInterfaces := strings.Join(opt.interfaceNames, ",")
	return fmt.Sprintf(
		"//go:generate %s -destination %s -package %s %s %s",
		opt.mockgenCmd,
		opt.destination,
		opt.packageName,
		opt.sourcePackage,
		joinedInterfaces,
	)
}

func writeOutTo(w io.Writer, sourcePkg string, opt *dumpCommentOption) {
	w.Write([]byte(fmt.Sprintf("package %s\n", sourcePkg)))
	w.Write([]byte("// Code generated by mockgengen. DO NOT EDIT.\n\n"))
	w.Write([]byte(dumpComment(opt) + "\n"))
}
